module.exports = {
  ROLES: {
    ADMIN: 'Admin',
    GENERAL_USER: 'General User',
  },
  VERIFICATION_STATUSES: ['Pending', 'Verified', 'Rejected'],
  VERIFICATION_TYPES: [
    'Employment History',
    'Education Verification',
    'Criminal Background',
    'Reference Check',
    'Identity Verification',
    'Address Verification',
    'Credit Check',
    'Drug Screening',
    'Professional License',
    'Social Media Screening',
  ],
  COMPANIES: [
    'Google',
    'Microsoft',
    'Amazon',
    'Meta',
    'Apple',
    'Netflix',
    'Salesforce',
    'Adobe',
    'Oracle',
    'IBM',
    'Infosys',
    'TCS',
    'Wipro',
    'Accenture',
    'Deloitte',
  ],
  ACCESS_LEVELS: ['Level 1', 'Level 2', 'Level 3', 'Confidential'],
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
  },
};
